-- bonezz_drugs/config.lua
BonezzDrugs = {
  Items = {
    ['weed_baggie'] = { label = 'Weed (Baggie)', weight = 1, type = 'item', image = 'weed_baggie.png', unique = false, useable = true, description = '' },
    ['weed_oz'] = { label = 'Weed (Ounce)', weight = 28, type = 'item', image = 'weed_oz.png', unique = false, useable = true, description = '' },
    ['weed_brick'] = { label = 'Weed (Brick)', weight = 500, type = 'item', image = 'weed_brick.png', unique = false, useable = true, description = '' },
    ['coke_baggie'] = { label = 'Cocaine (Baggie)', weight = 1, type = 'item', image = 'coke_baggie.png', unique = false, useable = true, description = '' },
    ['coke_oz'] = { label = 'Cocaine (Ounce)', weight = 28, type = 'item', image = 'coke_oz.png', unique = false, useable = true, description = '' },
    ['coke_brick'] = { label = 'Cocaine (Brick)', weight = 500, type = 'item', image = 'coke_brick.png', unique = false, useable = true, description = '' },
    ['meth_baggie'] = { label = 'Meth (Baggie)', weight = 1, type = 'item', image = 'meth_baggie.png', unique = false, useable = true, description = '' },
    ['meth_oz'] = { label = 'Meth (Ounce)', weight = 28, type = 'item', image = 'meth_oz.png', unique = false, useable = true, description = '' },
    ['meth_brick'] = { label = 'Meth (Brick)', weight = 500, type = 'item', image = 'meth_brick.png', unique = false, useable = true, description = '' },
    ['heroin_baggie'] = { label = 'Heroin (Baggie)', weight = 1, type = 'item', image = 'heroin_baggie.png', unique = false, useable = true, description = '' },
    ['heroin_oz'] = { label = 'Heroin (Ounce)', weight = 28, type = 'item', image = 'heroin_oz.png', unique = false, useable = true, description = '' },
    ['heroin_brick'] = { label = 'Heroin (Brick)', weight = 500, type = 'item', image = 'heroin_brick.png', unique = false, useable = true, description = '' },
    ['lsd_tab'] = { label = 'LSD (Tab)', weight = 1, type = 'item', image = 'lsd_tab.png', unique = false, useable = true, description = '' },
    ['shrooms'] = { label = 'Psilocybin Mushrooms', weight = 3, type = 'item', image = 'shrooms.png', unique = false, useable = true, description = '' },
    ['dmt_vial'] = { label = 'DMT (Vial)', weight = 1, type = 'item', image = 'dmt_vial.png', unique = false, useable = true, description = '' },
    ['mdma_pill'] = { label = 'MDMA (Pill)', weight = 1, type = 'item', image = 'mdma_pill.png', unique = false, useable = true, description = '' },
    ['mdma_baggie'] = { label = 'MDMA (Baggie)', weight = 2, type = 'item', image = 'mdma_baggie.png', unique = false, useable = true, description = '' },
    ['ketamine_baggie'] = { label = 'Ketamine (Baggie)', weight = 1, type = 'item', image = 'ketamine_baggie.png', unique = false, useable = true, description = '' },
    ['oxy'] = { label = 'Oxycodone', weight = 1, type = 'item', image = 'oxy.png', unique = false, useable = true, description = '' },
    ['xanax'] = { label = 'Xanax', weight = 1, type = 'item', image = 'xanax.png', unique = false, useable = true, description = '' },
    ['adderall'] = { label = 'Adderall', weight = 1, type = 'item', image = 'adderall.png', unique = false, useable = true, description = '' },
    ['fentanyl_powder'] = { label = 'Fentanyl (Powder)', weight = 1, type = 'item', image = 'fentanyl_powder.png', unique = false, useable = true, description = '' }
  },
  Prices = {
  "weed_baggie": 121,
  "weed_oz": 3320,
  "weed_brick": 38800,
  "coke_baggie": 162,
  "coke_oz": 6320,
  "coke_brick": 124800,
  "meth_baggie": 376,
  "meth_oz": 5360,
  "meth_brick": 94400,
  "heroin_baggie": 348,
  "heroin_oz": 3560,
  "heroin_brick": 74400,
  "lsd_tab": 212,
  "shrooms": 310,
  "dmt_vial": 260,
  "mdma_pill": 300,
  "mdma_baggie": 267,
  "ketamine_baggie": 145,
  "oxy": 122,
  "xanax": 121,
  "adderall": 119,
  "fentanyl_powder": 612
},
  SellbackMultiplier = 0.6,
}
